[package]
name = "odr-cli"
description = "ODR (Open Data Removal) command-line interface"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "odr"
path = "src/main.rs"

[dependencies]
odr-recipes = { workspace = true, features = ["schema-gen"] }
odr-engine.workspace = true
odr-server.workspace = true
serde.workspace = true
serde_yaml_ng.workspace = true
clap.workspace = true
anyhow.workspace = true
chrono.workspace = true
